name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go 1.18
        uses: actions/setup-go@v5
        with:
          go-version: 1.18
        id: go

      - name: checkout
        uses: actions/checkout@v4

      - name: build and test
        run: |
          go get -v ./...
          go test -timeout=60s -race -coverprofile=.coverage.out ./...

      - name: submit coverage file to codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report --force-coverage-parser go -r .coverage.out
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
